### ISSUE TITLE
Auto assigned properties on the Order object

### ISSUE THREAD

**Issue by tormnator** [TeaCommerce/Tea-Commerce-Documentation#2]
Here are couple Tea Commerce "features" which should be added to the documentation:

**Auto assigned properties on the Order object**

* `Order.CustomerId` - If a user is signed in (as evidenced by Membership.GetUser()) at the time the [GeneratePaymentForm()][1] method is called, then User.ProviderUserKey is assigned to Order.CustomerId.
* `Order.PaymentInformation.FirstName`, `PaymentInformation.LastName`, and `PaymentInformation.Email` - if you add "firstName", "lastName", and "email" properties to the order's custom properties, then these properties will be assigned to the respective PaymentInformation properties whenever the order is saved. These PaymentInformation properties end up being saved as FirstName, LastName, and Email fields in the TeaCommerce_Order table in the database. The typical place to define the custom properties is via the call to `AddOrUpdateOrderProperties` as [documented in Tea Commerce][2].

  [1]: https://docs.teacommerce.net/3.0.0/api/payment-provider/#generatepaymentform
  [2]: https://docs.teacommerce.net/3.0.0/api/order-property/#addorupdateorderproperty

**Comment by tormnator** [comment]
If you're using the default UmbracoMembershipProvider, then Membership.GetUser().ProviderUserKey will contain the umbraco member's Id, i.e. IMember.Id. This is an int value. It's worth noting that IMember.ProviderUserKey should **not** be used since that contains a Guid (maybe a reference to the underlying Asp.Net membership provider?). IMember is the entity you're dealing with when accessing member information via the Umbraco MemberService.

**Comment by mattbrailsford** [comment]
I believe `Membership.GetUser().ProviderUserKey` is used as this is the MembershipProvider way of getting the members ID. If it was tied to IMember implementation then this wouldn't work for other, non Umbraco memebrship providers. By using ProviderUserKey this would allow it to work with any membership provider.

If we need to discuss implementation details further, I suggest this aspect of this issue gets moved to the UI github repository as this is more about a code issue, than a docs issue.

**Comment by mattbrailsford** [comment]
Added docs to System Properties heading to the Order Properties section to document this.

http://localhost:8080/3.0.0/api/order-property/#system-properties
